application:
  security:
    jwt:
      secret-key: McvbiIKwPaVhmK8wFUDhXwZxvFlWeAzgaJ8XJr6cBsbWkPl9VUwAIww7GzFMV6zhISt6cwI3IFs
      expiration: 86400000
      refresh-token:
        expiration: 604800000
    mercado-pago:
      token: "TEST-4211162623316355-102721-97f8c196de766afb34090ba96b94a954-187606246"